### ISSUE TITLE
Bump GTK version

### ISSUE THREAD

**Issue by baarkerlounger** [SeaDve/plotters-gtk4#2]
Could you do a bump and release for compatibility with gtk-rs 0.9?

**Comment by Vectornaut** [comment]
I need this too, because I can't get `gtk-rs ^0.8` to compile. Is there any way to work around this, or will `plotters-gtk4` be unusable for me until the version bump goes through?

**Comment by SeaDve** [comment]
Fixed via https://github.com/SeaDve/plotters-gtk4/commit/c273fff577b4fe5f1c27811533860c7dcb7b3b3f

**Comment by SeaDve** [comment]
I also did a release. It should be available on `v0.5.0`

**Comment by baarkerlounger** [comment]
Mind doing this again for `0.10`?
